21858/add transactions
QuantuMobileSoftware/geoap pull request #355
Opened 2023-03-22 12:48 UTC by StanislavKharkiv

2023-03-22 13:54 UTC, avakin requested changes

2023-03-31 12:16 UTC, avakin commented on webviewer/src/pages/Account/components/Transactions/Transactions.jsx
> +              : `${t.amount == 0 ? '' : '+'} $${t.amount}`;
== is a mistake or needed to handle  string value like "0"?

2023-03-31 17:32 UTC, avakin approved these changes

2023-04-03 16:22 UTC, adolgarev approved these changes

2023-04-03 16:22 UTC, merged